{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "branch-heavy.fullname" . }}
  labels:
    {{- include "branch-heavy.labels" . | nindent 4 }}
  annotations:
    summary: {{ tpl .Values.service.summary . | quote }}
spec:
  selector:
{{ with .Values.labels }}
{{ range $k, $v := . }}
    {{ $k }}: {{ $v | quote }}
{{ else }}
    app: none
{{ end }}
{{ else }}
    app: none
{{ end }}
  ports:
{{ range .Values.ports }}
    - port: {{ . }}
{{ else }}
    - port: 0
{{ end }}
{{- if .Capabilities.APIVersions.Has "v1" }}
  type: {{ .Values.service.type | default "ClusterIP" }}
{{- end }}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "branch-heavy.fullname" . }}-disabled
{{ end }}
