apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-b.fullname" . }}
  labels:
    {{- include "chart-b.labels" . | nindent 4 }}
data:
  mode: {{ if eq .Values.deploymentMode "prod" }}"prod"{{ else }}"dev"{{ end }}
  target: {{ tpl .Values.target . | quote }}
  {{- if semverCompare ">=1.25.0" .Capabilities.KubeVersion.GitVersion }}
  modernCluster: "true"
  {{- end }}
